# PhD Workflow Configuration

# NOTE: This file contains default configurations and examples. Some settings 
# (particularly paths) are automatically configured during installation and don't
# need to be modified here.

# Default environments - Naming convention for Conda environments
# The 'ML_exp' environment is attempted to be activated in experiment mode
environments:
  # You can create this environment manually:
  # conda create -n ML_exp python=3.9 numpy pandas matplotlib jupyter tensorflow pytorch
  ML_exp:
    description: Default environment for ML experiments
    packages:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - jupyter
      - tensorflow
      - pytorch
  
  climate:
    description: Optional environment for climate modeling
    packages:
      - numpy
      - pandas
      - xarray
      - netcdf4
      - cartopy
      - jupyter

# GitHub configuration (Currently uses gh CLI authentication)
# These settings are not actively used but serve as documentation
github:
  username: # Your GitHub username (populated by gh CLI)
  email: # Your GitHub email (populated by gh CLI)
  organization: # Optional organization name

# AWS configuration (Used when AWS mode is activated)
aws:
  default_region: us-east-1
  default_bucket_prefix: phd- # Bucket names will be prefixed with this
  profile: default
  use_metaflow: true
  metaflow:
    datastore: s3
    metadata: service

# Tools configuration
tools:
  default_mode: experiment 